const map=L.map('map').setView([51.5340,-0.2050],15.2);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);

const cfg=window.HS2_MAP_CONFIG||{};
let routeFeature=null, routeCoords=[];
let tunnelLayer=L.layerGroup().addTo(map);
let zoneLayer=L.layerGroup().addTo(map);
const markerLayer=L.layerGroup().addTo(map);
let properties=[];

const samples=[
['01','Sample property – Kilburn Lane','',51.5351,-0.2057,'Sample only'],['02','Sample property – Kilburn Lane','',51.5350,-0.2047,'Sample only'],['03','Sample property – Kilburn Lane','',51.5349,-0.2037,'Sample only'],['04','Sample property – Kilburn Lane','',51.5348,-0.2027,'Sample only'],
['05','Sample property – Bravington Road','',51.5337,-0.2091,'Sample only'],['06','Sample property – Bravington Road','',51.5331,-0.2089,'Sample only'],['07','Sample property – Bravington Road','',51.5325,-0.2087,'Sample only'],['08','Sample property – Bravington Road','',51.5319,-0.2085,'Sample only'],
['09','Sample property – Portnall Road','',51.5342,-0.2012,'Sample only'],['10','Sample property – Portnall Road','',51.5336,-0.2010,'Sample only'],['11','Sample property – Portnall Road','',51.5330,-0.2008,'Sample only'],['12','Sample property – Portnall Road','',51.5324,-0.2006,'Sample only'],
['13','Sample property – Ashmore Road','',51.5325,-0.1969,'Sample only'],['14','Sample property – Ashmore Road','',51.5320,-0.1967,'Sample only'],['15','Sample property – Ashmore Road','',51.5315,-0.1965,'Sample only'],['16','Sample property – Ashmore Road','',51.5310,-0.1963,'Sample only'],
['17','Sample property – Queen’s Park area','',51.5344,-0.2061,'Sample only'],['18','Sample property – Queen’s Park area','',51.5338,-0.2037,'Sample only'],['19','Sample property – Queen’s Park area','',51.5331,-0.1994,'Sample only'],['20','Sample property – Queen’s Park area','',51.5324,-0.1955,'Sample only']
].map(r=>({id:r[0],address:r[1],postcode:r[2],latitude:r[3],longitude:r[4],notes:r[5]}));

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toXY(lat,lon,refLat){const R=6371000,rad=Math.PI/180;return {x:lon*rad*R*Math.cos(refLat*rad),y:lat*rad*R}}
function pointSegDist(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,den=dx*dx+dy*dy;let t=den?((p.x-a.x)*dx+(p.y-a.y)*dy)/den:0;t=Math.max(0,Math.min(1,t));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy))}
function tunnelDistance(lat,lon){if(routeCoords.length<2)return NaN;const ref=lat,p=toXY(lat,lon,ref);let d=Infinity;for(let i=0;i<routeCoords.length-1;i++){const a=routeCoords[i],b=routeCoords[i+1];d=Math.min(d,pointSegDist(p,toXY(a[0],a[1],ref),toXY(b[0],b[1],ref)))}return d}
function classify(d){return d<=8?'very-close':d<=30?'within-30':'outside-30'}
function iconFor(p){return L.divIcon({className:'',html:`<span class="house-marker ${p.status}">${esc(p.id)}</span>`,iconSize:[28,28],iconAnchor:[14,14]})}
function render(){markerLayer.clearLayers();const q=document.querySelector('#search').value.toLowerCase().trim(),filter=document.querySelector('#status').value;let visible=0;properties.forEach(p=>{if(!(Number.isFinite(+p.latitude)&&Number.isFinite(+p.longitude)))return;p.distance=tunnelDistance(+p.latitude,+p.longitude);p.status=Number.isFinite(p.distance)?classify(p.distance):'outside-30';const text=`${p.id} ${p.address} ${p.postcode||''}`.toLowerCase();if((q&&!text.includes(q))||(filter!=='all'&&p.status!==filter))return;visible++;const m=L.marker([+p.latitude,+p.longitude],{icon:iconFor(p)}).addTo(markerLayer);m.bindTooltip(p.address);m.on('click',()=>showDetails(p))});const counts={very:properties.filter(p=>p.status==='very-close').length,within:properties.filter(p=>p.status==='within-30').length,out:properties.filter(p=>p.status==='outside-30').length};document.querySelector('#summary').innerHTML=`<b>${visible}</b> shown of ${properties.length}<br>Located: ${validProperties().length} · Unresolved: ${properties.length-validProperties().length}<br>Very close: ${counts.very} · Within 30 m: ${counts.within} · Outside: ${counts.out}`}
function showDetails(p){document.querySelector('#details').innerHTML=`<h2>Selected property</h2><p><strong>${esc(p.address)}</strong></p><p>ID: ${esc(p.id)}${p.postcode?` · ${esc(p.postcode)}`:''}</p><p>Approx. distance to mapped HS2 tunnel route: <strong>${Number.isFinite(p.distance)?p.distance.toFixed(1)+' m':'—'}</strong></p><p>Status: <strong>${p.status==='very-close'?'Very close / above':p.status==='within-30'?'Within 30 m':'Outside 30 m'}</strong></p><p>${esc(p.notes||'')}</p><p class="hint">Distance is a screening aid, not an HS2 eligibility determination.</p>`}
function splitCSV(line){let out=[],v='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){out.push(v.trim());v=''}else v+=c}out.push(v.trim());return out}
function normaliseHeader(x){return String(x||'').toLowerCase().trim().replace(/[ _-]+/g,'')}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw Error('The sheet has no data rows.');const raw=splitCSV(lines[0]);const aliases={id:['id','propertyid','ref','reference'],address:['address','propertyaddress','houseaddress'],postcode:['postcode','postalcode','zip'],latitude:['latitude','lat'],longitude:['longitude','lng','lon','long'],notes:['notes','note','comments','comment']};const idx={};raw.forEach((h,i)=>{const n=normaliseHeader(h);for(const [key,vals] of Object.entries(aliases))if(vals.includes(n))idx[key]=i});if(idx.address===undefined)throw Error('Missing required column: Address.');const rows=[];lines.slice(1).forEach((line,i)=>{const a=splitCSV(line);if(!a.some(Boolean))return;const get=k=>idx[k]===undefined?'':(a[idx[k]]??'').trim();if(!get('address'))return;const lat=parseFloat(get('latitude')),lon=parseFloat(get('longitude'));rows.push({id:get('id')||String(rows.length+1).padStart(2,'0'),address:get('address'),postcode:get('postcode'),latitude:Number.isFinite(lat)?lat:null,longitude:Number.isFinite(lon)?lon:null,notes:get('notes'),rowNumber:i+2})});if(!rows.length)throw Error('No usable property rows were found.');return rows}
function cacheKey(p){return 'hs2qp:geocode:'+String(p.address+' '+(p.postcode||'')).toLowerCase().replace(/\s+/g,' ').trim()}
function readGeocodeCache(p){try{const v=JSON.parse(localStorage.getItem(cacheKey(p)));if(v&&Number.isFinite(v.lat)&&Number.isFinite(v.lon)){p.latitude=v.lat;p.longitude=v.lon;return true}}catch(e){}return false}
function saveGeocodeCache(p){try{localStorage.setItem(cacheKey(p),JSON.stringify({lat:+p.latitude,lon:+p.longitude,display:p.geocodeDisplay||'',saved:Date.now()}))}catch(e){}}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function geocodeOne(p){const query=[p.address,p.postcode,'London','UK'].filter(Boolean).join(', ');const base=cfg.geocoderUrl||'https://nominatim.openstreetmap.org/search';const url=base+'?format=jsonv2&limit=1&countrycodes=gb&q='+encodeURIComponent(query);const res=await fetch(url,{headers:{'Accept':'application/json'}});if(!res.ok)throw Error('Geocoder HTTP '+res.status);const data=await res.json();if(!data.length)return false;const lat=Number(data[0].lat),lon=Number(data[0].lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return false;p.latitude=lat;p.longitude=lon;p.geocodeDisplay=data[0].display_name||'';saveGeocodeCache(p);return true}
async function resolveMissingCoordinates(rows){const missing=rows.filter(p=>!(Number.isFinite(+p.latitude)&&Number.isFinite(+p.longitude)));missing.forEach(readGeocodeCache);const todo=missing.filter(p=>!(Number.isFinite(+p.latitude)&&Number.isFinite(+p.longitude)));if(!todo.length)return {resolved:missing.length,failed:[]};const failed=[];for(let i=0;i<todo.length;i++){const p=todo[i];setDataStatus(`Locating address ${i+1} of ${todo.length}: ${p.address}${p.postcode?' · '+p.postcode:''}…`,'loading');try{if(!await geocodeOne(p))failed.push(p)}catch(e){failed.push(p)}if(i<todo.length-1)await sleep(Math.max(1100,cfg.geocodeDelayMs||1100))}return {resolved:missing.length-failed.length,failed}}
function validProperties(){return properties.filter(p=>Number.isFinite(+p.latitude)&&Number.isFinite(+p.longitude))}
function showUnresolved(failed){const el=document.querySelector('#unresolved');if(!failed.length){el.innerHTML='';return}el.innerHTML=`<details open><summary>${failed.length} address${failed.length===1?'':'es'} could not be located</summary><ul>${failed.map(p=>`<li>${esc(p.address)}${p.postcode?' · '+esc(p.postcode):''}</li>`).join('')}</ul><p class=\"hint\">Check the spelling/postcode in the Google Sheet, then click Reload Google Sheet.</p></details>`}

function setDataStatus(message,kind=''){const el=document.querySelector('#dataStatus');el.textContent=message;el.className='data-status '+kind}
function sheetCsvUrl(){return cfg.spreadsheetId?`https://docs.google.com/spreadsheets/d/${encodeURIComponent(cfg.spreadsheetId)}/export?format=csv&gid=${encodeURIComponent(cfg.sheetGid||'0')}`:''}
function fitAll(){const pts=validProperties().map(p=>[+p.latitude,+p.longitude]);routeCoords.forEach(p=>pts.push(p));if(pts.length)map.fitBounds(pts,{padding:[35,35],maxZoom:16})}
async function loadGoogleSheet(){const url=sheetCsvUrl();if(!url){setDataStatus('No Google Sheet is configured.','error');return}setDataStatus('Loading properties from Google Sheet…','loading');try{const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw Error(`Google returned HTTP ${res.status}`);properties=parseCSV(await res.text());const geo=await resolveMissingCoordinates(properties);render();fitAll();showUnresolved(geo.failed);setDataStatus(`${properties.length} properties loaded from Google Sheet · ${validProperties().length} located · ${new Date().toLocaleString('en-GB')}`,'ok')}catch(err){properties=samples.map(x=>({...x}));render();setDataStatus(`Google Sheet could not be loaded: ${err.message} Showing 20 sample properties instead.`,'error')}}
async function loadRoute(){try{const res=await fetch('hs2-route.geojson',{cache:'no-store'});if(!res.ok)throw Error(`HTTP ${res.status}`);const gj=await res.json();routeFeature=gj.features[0];routeCoords=routeFeature.geometry.coordinates.map(c=>[c[1],c[0]]);tunnelLayer.clearLayers();zoneLayer.clearLayers();if(window.turf){
      L.geoJSON(routeFeature,{style:{color:'#111',weight:5,opacity:.92,dashArray:'14 10',lineCap:'butt'}})
        .bindPopup('<strong>HS2 Euston Tunnel route</strong><br>Digitised from the supplied official HS2 Queen’s Park route plan. Reference trace only; not survey/legal geometry.').addTo(tunnelLayer);
      L.geoJSON(routeFeature,{style:{color:'#fff',weight:2,opacity:.95,dashArray:'14 10',dashOffset:'12',lineCap:'butt'}}).addTo(tunnelLayer);
      const buffered=turf.buffer(routeFeature,0.03,{units:'kilometers'});
      L.geoJSON(buffered,{style:{color:'#2f6fb3',weight:1,opacity:.55,fillColor:'#7fb3e6',fillOpacity:.13}})
        .bindPopup('<strong>30 m screening zone</strong><br>Approximate 30 m map-screening buffer around the digitised tunnel route. It is not an official HS2 eligibility boundary.').addTo(zoneLayer)
    }else{L.geoJSON(routeFeature,{style:{color:'#111',weight:4,dashArray:'12 8'}}).addTo(tunnelLayer)}document.querySelector('#routeStatus').textContent='Route: digitised from supplied HS2 Queen’s Park tunnel plan (reference trace).';render();fitAll()}catch(err){document.querySelector('#routeStatus').textContent='HS2 route layer could not be loaded: '+err.message}}

document.querySelector('#search').addEventListener('input',render);document.querySelector('#status').addEventListener('change',render);
document.querySelector('#showTunnel').addEventListener('change',e=>e.target.checked?tunnelLayer.addTo(map):map.removeLayer(tunnelLayer));document.querySelector('#showZone').addEventListener('change',e=>e.target.checked?zoneLayer.addTo(map):map.removeLayer(zoneLayer));document.querySelector('#showHouses').addEventListener('change',e=>e.target.checked?markerLayer.addTo(map):map.removeLayer(markerLayer));
document.querySelector('#reloadSheet').addEventListener('click',loadGoogleSheet);
document.querySelector('#restore').addEventListener('click',()=>{properties=samples.map(x=>({...x}));document.querySelector('#csvFile').value='';render();fitAll();setDataStatus('Showing 20 sample properties.','')});
document.querySelector('#csvFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{properties=parseCSV(await f.text());const geo=await resolveMissingCoordinates(properties);render();fitAll();showUnresolved(geo.failed);setDataStatus(`${properties.length} properties loaded from local CSV · ${validProperties().length} located.`,'ok')}catch(err){alert('Could not import CSV: '+err.message);e.target.value=''}});
properties=samples.map(x=>({...x}));render();loadRoute().then(()=>{if(cfg.useGoogleSheet!==false)loadGoogleSheet();else setDataStatus('Google Sheet loading is disabled; showing sample properties.','')});
