const map=L.map('map').setView([51.536,-0.205],15.5);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);

// PROVISIONAL prototype geometry only — replace with verified HS2 GeoJSON.
const tunnelCoords=[[51.53835,-0.2164],[51.53905,-0.2110],[51.53920,-0.2050],[51.53875,-0.1985],[51.53780,-0.1915]];
const tunnel=L.polyline(tunnelCoords,{color:'#174a9c',weight:7,opacity:.95}).addTo(map);
// Leaflet has no geodesic line buffer; this wide translucent line is a visual proxy only.
const zone=L.polyline(tunnelCoords,{color:'#e05a64',weight:44,opacity:.28,lineCap:'round'}).addTo(map); tunnel.bringToFront();

const samples=[
['01','Sample House 01 – Kilburn Lane','',51.53855,-0.2109,'Sample only'],['02','Sample House 02 – Kilburn Lane','',51.53870,-0.2098,'Sample only'],['03','Sample House 03 – Kilburn Lane','',51.53872,-0.2086,'Sample only'],['04','Sample House 04 – Kilburn Lane','',51.53855,-0.2074,'Sample only'],
['05','Sample House 05 – Bravington Road','',51.53795,-0.2047,'Sample only'],['06','Sample House 06 – Bravington Road','',51.53725,-0.2046,'Sample only'],['07','Sample House 07 – Bravington Road','',51.53655,-0.2045,'Sample only'],['08','Sample House 08 – Bravington Road','',51.53585,-0.2044,'Sample only'],
['09','Sample House 09 – Portnall Road','',51.53785,-0.2018,'Sample only'],['10','Sample House 10 – Portnall Road','',51.53715,-0.2017,'Sample only'],['11','Sample House 11 – Portnall Road','',51.53645,-0.2016,'Sample only'],['12','Sample House 12 – Portnall Road','',51.53575,-0.2015,'Sample only'],
['13','Sample House 13 – Ashmore Road','',51.53765,-0.1988,'Sample only'],['14','Sample House 14 – Ashmore Road','',51.53695,-0.1987,'Sample only'],['15','Sample House 15 – Ashmore Road','',51.53625,-0.1986,'Sample only'],['16','Sample House 16 – Ashmore Road','',51.53555,-0.1985,'Sample only'],
['17','Sample House 17 – Queen’s Park area','',51.53825,-0.2132,'Sample only'],['18','Sample House 18 – Queen’s Park area','',51.53765,-0.2122,'Sample only'],['19','Sample House 19 – Queen’s Park area','',51.53525,-0.2075,'Sample only'],['20','Sample House 20 – Queen’s Park area','',51.53495,-0.1995,'Sample only']
].map(r=>({id:r[0],address:r[1],postcode:r[2],latitude:r[3],longitude:r[4],notes:r[5]}));

let properties=samples.map(x=>({...x})); const markerLayer=L.layerGroup().addTo(map); let markers=[];
const cfg=window.HS2_MAP_CONFIG||{};
function toXY(lat,lon,refLat){const R=6371000,rad=Math.PI/180;return {x:lon*rad*R*Math.cos(refLat*rad),y:lat*rad*R}}
function pointSegDist(p,a,b){const dx=b.x-a.x,dy=b.y-a.y;const den=dx*dx+dy*dy;let t=den?((p.x-a.x)*dx+(p.y-a.y)*dy)/den:0;t=Math.max(0,Math.min(1,t));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy))}
function tunnelDistance(lat,lon){const ref=lat,p=toXY(lat,lon,ref);let d=Infinity;for(let i=0;i<tunnelCoords.length-1;i++)d=Math.min(d,pointSegDist(p,toXY(...tunnelCoords[i],ref),toXY(...tunnelCoords[i+1],ref)));return d}
function classify(d){return d<=8?'very-close':d<=30?'within-30':'outside-30'}
function iconFor(p){return L.divIcon({className:'',html:`<span class="house-marker ${p.status}">${esc(p.id)}</span>`,iconSize:[28,28],iconAnchor:[14,14]})}
function render(){markerLayer.clearLayers();markers=[];const q=document.querySelector('#search').value.toLowerCase().trim(),filter=document.querySelector('#status').value;let visible=0;properties.forEach(p=>{p.distance=tunnelDistance(+p.latitude,+p.longitude);p.status=classify(p.distance);const text=`${p.id} ${p.address} ${p.postcode||''}`.toLowerCase();if((q&&!text.includes(q))||(filter!=='all'&&p.status!==filter))return;visible++;const m=L.marker([+p.latitude,+p.longitude],{icon:iconFor(p)}).addTo(markerLayer);m.bindTooltip(p.address);m.on('click',()=>showDetails(p));markers.push(m)});const counts={very:properties.filter(p=>p.status==='very-close').length,within:properties.filter(p=>p.status==='within-30').length,out:properties.filter(p=>p.status==='outside-30').length};document.querySelector('#summary').innerHTML=`<b>${visible}</b> shown of ${properties.length}<br>Very close: ${counts.very} · Within 30 m: ${counts.within} · Outside: ${counts.out}`}
function showDetails(p){document.querySelector('#details').innerHTML=`<h2>Selected property</h2><p><strong>${esc(p.address)}</strong></p><p>ID: ${esc(p.id)}${p.postcode?` · ${esc(p.postcode)}`:''}</p><p>Approx. distance to provisional alignment: <strong>${p.distance.toFixed(1)} m</strong></p><p>Status: <strong>${p.status==='very-close'?'Very close / above':p.status==='within-30'?'Within 30 m':'Outside 30 m'}</strong></p><p>${esc(p.notes||'')}</p>`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function splitCSV(line){let out=[],v='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){out.push(v.trim());v=''}else v+=c}out.push(v.trim());return out}
function normaliseHeader(x){return String(x||'').toLowerCase().trim().replace(/[ _-]+/g,'')}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw Error('The sheet has no data rows.');const raw=splitCSV(lines[0]);const aliases={id:['id','propertyid','ref','reference'],address:['address','propertyaddress','houseaddress'],postcode:['postcode','postalcode','zip'],latitude:['latitude','lat'],longitude:['longitude','lng','lon','long'],notes:['notes','note','comments','comment']};const idx={};raw.forEach((h,i)=>{const n=normaliseHeader(h);for(const [key,vals] of Object.entries(aliases))if(vals.includes(n))idx[key]=i});for(const req of ['address','latitude','longitude'])if(idx[req]===undefined)throw Error(`Missing required column: ${req}. Address, Latitude and Longitude are currently required.`);const rows=[];lines.slice(1).forEach((line,i)=>{const a=splitCSV(line);if(!a.some(Boolean))return;const get=k=>idx[k]===undefined?'':(a[idx[k]]??'').trim();const lat=Number(get('latitude')),lon=Number(get('longitude'));if(!get('address'))return;if(!Number.isFinite(lat)||!Number.isFinite(lon))throw Error(`Invalid coordinates on data row ${i+2}`);rows.push({id:get('id')||String(rows.length+1).padStart(2,'0'),address:get('address'),postcode:get('postcode'),latitude:lat,longitude:lon,notes:get('notes')})});if(!rows.length)throw Error('No usable property rows were found.');return rows}
function setDataStatus(message,kind=''){const el=document.querySelector('#dataStatus');el.textContent=message;el.className='data-status '+kind}
function sheetCsvUrl(){if(!cfg.spreadsheetId)return '';return `https://docs.google.com/spreadsheets/d/${encodeURIComponent(cfg.spreadsheetId)}/export?format=csv&gid=${encodeURIComponent(cfg.sheetGid||'0')}`}
function fitProperties(){const pts=properties.map(p=>[+p.latitude,+p.longitude]).filter(p=>p.every(Number.isFinite));if(pts.length)map.fitBounds(pts,{padding:[30,30],maxZoom:17})}
async function loadGoogleSheet(){const url=sheetCsvUrl();if(!url){setDataStatus('No Google Sheet is configured.','error');return}setDataStatus('Loading properties from Google Sheet…','loading');try{const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw Error(`Google returned HTTP ${res.status}`);const text=await res.text();properties=parseCSV(text);render();fitProperties();setDataStatus(`${properties.length} properties loaded from Google Sheet.`,'ok')}catch(err){properties=samples.map(x=>({...x}));render();setDataStatus(`Google Sheet could not be loaded: ${err.message} Showing 20 sample properties instead.`,'error')}}

document.querySelector('#search').addEventListener('input',render);document.querySelector('#status').addEventListener('change',render);
document.querySelector('#showTunnel').addEventListener('change',e=>e.target.checked?tunnel.addTo(map):map.removeLayer(tunnel));document.querySelector('#showZone').addEventListener('change',e=>e.target.checked?zone.addTo(map):map.removeLayer(zone));document.querySelector('#showHouses').addEventListener('change',e=>e.target.checked?markerLayer.addTo(map):map.removeLayer(markerLayer));
document.querySelector('#reloadSheet').addEventListener('click',loadGoogleSheet);
document.querySelector('#restore').addEventListener('click',()=>{properties=samples.map(x=>({...x}));document.querySelector('#csvFile').value='';render();map.setView([51.536,-0.205],15.5);setDataStatus('Showing 20 sample properties.','')});
document.querySelector('#csvFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{properties=parseCSV(await f.text());render();fitProperties();setDataStatus(`${properties.length} properties loaded from local CSV.`,'ok')}catch(err){alert('Could not import CSV: '+err.message);e.target.value=''}});
render();if(cfg.useGoogleSheet!==false)loadGoogleSheet();else setDataStatus('Google Sheet loading is disabled; showing sample properties.','');
