const map=L.map('map').setView([51.5340,-0.2050],15.2);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);

const cfg=window.HS2_MAP_CONFIG||{};
let routeFeature=null, routeCoords=[];
let tunnelLayer=L.layerGroup().addTo(map);
let zoneLayer=L.layerGroup().addTo(map);
const markerLayer=L.layerGroup().addTo(map);
let properties=[];

const samples=[
['01','Sample property – Kilburn Lane','',51.5351,-0.2057,'Sample only'],['02','Sample property – Kilburn Lane','',51.5350,-0.2047,'Sample only'],['03','Sample property – Kilburn Lane','',51.5349,-0.2037,'Sample only'],['04','Sample property – Kilburn Lane','',51.5348,-0.2027,'Sample only'],
['05','Sample property – Bravington Road','',51.5337,-0.2091,'Sample only'],['06','Sample property – Bravington Road','',51.5331,-0.2089,'Sample only'],['07','Sample property – Bravington Road','',51.5325,-0.2087,'Sample only'],['08','Sample property – Bravington Road','',51.5319,-0.2085,'Sample only'],
['09','Sample property – Portnall Road','',51.5342,-0.2012,'Sample only'],['10','Sample property – Portnall Road','',51.5336,-0.2010,'Sample only'],['11','Sample property – Portnall Road','',51.5330,-0.2008,'Sample only'],['12','Sample property – Portnall Road','',51.5324,-0.2006,'Sample only'],
['13','Sample property – Ashmore Road','',51.5325,-0.1969,'Sample only'],['14','Sample property – Ashmore Road','',51.5320,-0.1967,'Sample only'],['15','Sample property – Ashmore Road','',51.5315,-0.1965,'Sample only'],['16','Sample property – Ashmore Road','',51.5310,-0.1963,'Sample only'],
['17','Sample property – Queen’s Park area','',51.5344,-0.2061,'Sample only'],['18','Sample property – Queen’s Park area','',51.5338,-0.2037,'Sample only'],['19','Sample property – Queen’s Park area','',51.5331,-0.1994,'Sample only'],['20','Sample property – Queen’s Park area','',51.5324,-0.1955,'Sample only']
].map(r=>({id:r[0],address:r[1],postcode:r[2],latitude:r[3],longitude:r[4],notes:r[5]}));

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toXY(lat,lon,refLat){const R=6371000,rad=Math.PI/180;return {x:lon*rad*R*Math.cos(refLat*rad),y:lat*rad*R}}
function pointSegDist(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,den=dx*dx+dy*dy;let t=den?((p.x-a.x)*dx+(p.y-a.y)*dy)/den:0;t=Math.max(0,Math.min(1,t));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy))}
function tunnelDistance(lat,lon){if(routeCoords.length<2)return NaN;const ref=lat,p=toXY(lat,lon,ref);let d=Infinity;for(let i=0;i<routeCoords.length-1;i++){const a=routeCoords[i],b=routeCoords[i+1];d=Math.min(d,pointSegDist(p,toXY(a[0],a[1],ref),toXY(b[0],b[1],ref)))}return d}
function classify(d){return d<=8?'very-close':d<=30?'within-30':'outside-30'}
function iconFor(p){return L.divIcon({className:'',html:`<span class="house-marker ${p.status}">${esc(p.id)}</span>`,iconSize:[28,28],iconAnchor:[14,14]})}
function render(){markerLayer.clearLayers();const q=document.querySelector('#search').value.toLowerCase().trim(),filter=document.querySelector('#status').value;let visible=0;properties.forEach(p=>{p.distance=tunnelDistance(+p.latitude,+p.longitude);p.status=Number.isFinite(p.distance)?classify(p.distance):'outside-30';const text=`${p.id} ${p.address} ${p.postcode||''}`.toLowerCase();if((q&&!text.includes(q))||(filter!=='all'&&p.status!==filter))return;visible++;const m=L.marker([+p.latitude,+p.longitude],{icon:iconFor(p)}).addTo(markerLayer);m.bindTooltip(p.address);m.on('click',()=>showDetails(p))});const counts={very:properties.filter(p=>p.status==='very-close').length,within:properties.filter(p=>p.status==='within-30').length,out:properties.filter(p=>p.status==='outside-30').length};document.querySelector('#summary').innerHTML=`<b>${visible}</b> shown of ${properties.length}<br>Very close: ${counts.very} · Within 30 m: ${counts.within} · Outside: ${counts.out}`}
function showDetails(p){document.querySelector('#details').innerHTML=`<h2>Selected property</h2><p><strong>${esc(p.address)}</strong></p><p>ID: ${esc(p.id)}${p.postcode?` · ${esc(p.postcode)}`:''}</p><p>Approx. distance to mapped HS2 reference alignment: <strong>${Number.isFinite(p.distance)?p.distance.toFixed(1)+' m':'—'}</strong></p><p>Status: <strong>${p.status==='very-close'?'Very close / above':p.status==='within-30'?'Within 30 m':'Outside 30 m'}</strong></p><p>${esc(p.notes||'')}</p><p class="hint">Distance is a screening aid, not an HS2 eligibility determination.</p>`}
function splitCSV(line){let out=[],v='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){out.push(v.trim());v=''}else v+=c}out.push(v.trim());return out}
function normaliseHeader(x){return String(x||'').toLowerCase().trim().replace(/[ _-]+/g,'')}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw Error('The sheet has no data rows.');const raw=splitCSV(lines[0]);const aliases={id:['id','propertyid','ref','reference'],address:['address','propertyaddress','houseaddress'],postcode:['postcode','postalcode','zip'],latitude:['latitude','lat'],longitude:['longitude','lng','lon','long'],notes:['notes','note','comments','comment']};const idx={};raw.forEach((h,i)=>{const n=normaliseHeader(h);for(const [key,vals] of Object.entries(aliases))if(vals.includes(n))idx[key]=i});for(const req of ['address','latitude','longitude'])if(idx[req]===undefined)throw Error(`Missing required column: ${req}. Address, Latitude and Longitude are currently required.`);const rows=[];lines.slice(1).forEach((line,i)=>{const a=splitCSV(line);if(!a.some(Boolean))return;const get=k=>idx[k]===undefined?'':(a[idx[k]]??'').trim();const lat=Number(get('latitude')),lon=Number(get('longitude'));if(!get('address'))return;if(!Number.isFinite(lat)||!Number.isFinite(lon))throw Error(`Invalid coordinates on data row ${i+2}`);rows.push({id:get('id')||String(rows.length+1).padStart(2,'0'),address:get('address'),postcode:get('postcode'),latitude:lat,longitude:lon,notes:get('notes')})});if(!rows.length)throw Error('No usable property rows were found.');return rows}
function setDataStatus(message,kind=''){const el=document.querySelector('#dataStatus');el.textContent=message;el.className='data-status '+kind}
function sheetCsvUrl(){return cfg.spreadsheetId?`https://docs.google.com/spreadsheets/d/${encodeURIComponent(cfg.spreadsheetId)}/export?format=csv&gid=${encodeURIComponent(cfg.sheetGid||'0')}`:''}
function fitAll(){const pts=properties.map(p=>[+p.latitude,+p.longitude]).filter(p=>p.every(Number.isFinite));routeCoords.forEach(p=>pts.push(p));if(pts.length)map.fitBounds(pts,{padding:[35,35],maxZoom:16})}
async function loadGoogleSheet(){const url=sheetCsvUrl();if(!url){setDataStatus('No Google Sheet is configured.','error');return}setDataStatus('Loading properties from Google Sheet…','loading');try{const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw Error(`Google returned HTTP ${res.status}`);properties=parseCSV(await res.text());render();setDataStatus(`${properties.length} properties loaded from Google Sheet · ${new Date().toLocaleString('en-GB')}`,'ok')}catch(err){properties=samples.map(x=>({...x}));render();setDataStatus(`Google Sheet could not be loaded: ${err.message} Showing 20 sample properties instead.`,'error')}}
async function loadRoute(){try{const res=await fetch('hs2-route.geojson',{cache:'no-store'});if(!res.ok)throw Error(`HTTP ${res.status}`);const gj=await res.json();routeFeature=gj.features[0];routeCoords=routeFeature.geometry.coordinates.map(c=>[c[1],c[0]]);tunnelLayer.clearLayers();zoneLayer.clearLayers();L.geoJSON(gj,{style:{color:'#174a9c',weight:6,opacity:.95}}).bindPopup('<strong>HS2 Euston Tunnel</strong><br>Queen’s Park reference alignment digitised from the official 2024 HS2 safeguarding/property map.').addTo(tunnelLayer);if(window.turf){const buffered=turf.buffer(routeFeature,0.03,{units:'kilometers'});L.geoJSON(buffered,{style:{color:'#d9485f',weight:2,fillColor:'#e87886',fillOpacity:.18,dashArray:'7 5'}}).bindPopup('<strong>30 m screening buffer</strong><br>Measured from this reference alignment for map screening only. HS2 eligibility is based on distance from the relevant excavation and official assessment.').addTo(zoneLayer)}render();fitAll()}catch(err){document.querySelector('#routeStatus').textContent='HS2 route layer could not be loaded: '+err.message}}

document.querySelector('#search').addEventListener('input',render);document.querySelector('#status').addEventListener('change',render);
document.querySelector('#showTunnel').addEventListener('change',e=>e.target.checked?tunnelLayer.addTo(map):map.removeLayer(tunnelLayer));document.querySelector('#showZone').addEventListener('change',e=>e.target.checked?zoneLayer.addTo(map):map.removeLayer(zoneLayer));document.querySelector('#showHouses').addEventListener('change',e=>e.target.checked?markerLayer.addTo(map):map.removeLayer(markerLayer));
document.querySelector('#reloadSheet').addEventListener('click',loadGoogleSheet);
document.querySelector('#restore').addEventListener('click',()=>{properties=samples.map(x=>({...x}));document.querySelector('#csvFile').value='';render();fitAll();setDataStatus('Showing 20 sample properties.','')});
document.querySelector('#csvFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{properties=parseCSV(await f.text());render();fitAll();setDataStatus(`${properties.length} properties loaded from local CSV.`,'ok')}catch(err){alert('Could not import CSV: '+err.message);e.target.value=''}});
properties=samples.map(x=>({...x}));render();loadRoute().then(()=>{if(cfg.useGoogleSheet!==false)loadGoogleSheet();else setDataStatus('Google Sheet loading is disabled; showing sample properties.','')});
